package de.fabiexe.sjql.expression

infix fun Expression.eq(other: Expression): Expression = eq(other)
infix fun Expression.eq(value: Any?): Expression = eq(value)
infix fun Expression.neq(other: Expression): Expression = neq(other)
infix fun Expression.neq(value: Any?): Expression = neq(value)
infix fun Expression.gt(other: Expression): Expression = gt(other)
infix fun Expression.gt(value: Any?): Expression = gt(value)
infix fun Expression.gte(other: Expression): Expression = gte(other)
infix fun Expression.gte(value: Any?): Expression = gte(value)
infix fun Expression.lt(other: Expression): Expression = lt(other)
infix fun Expression.lt(value: Any?): Expression = lt(value)
infix fun Expression.lte(other: Expression): Expression = lte(other)
infix fun Expression.lte(value: Any?): Expression = lte(value)
infix fun Expression.and(other: Expression): Expression = and(other)
infix fun Expression.and(value: Any?): Expression = and(value)
infix fun Expression.or(other: Expression): Expression = or(other)
infix fun Expression.or(value: Any?): Expression = or(value)
infix fun Expression.xor(other: Expression): Expression = xor(other)
infix fun Expression.xor(value: Any?): Expression = xor(value)