package de.fabiexe.sjql.database;

import de.fabiexe.sjql.*;
import de.fabiexe.sjql.column.*;
import de.fabiexe.sjql.expression.Expression;
import de.fabiexe.sjql.expression.constant.ConstantExpression;
import de.fabiexe.sjql.query.BasicDeleteStatement;
import de.fabiexe.sjql.query.BasicRowQuery;
import de.fabiexe.sjql.query.BasicUpdateStatement;
import de.fabiexe.sjql.query.BasicValueQuery;
import de.fabiexe.sjql.row.ReadableRow;
import de.fabiexe.sjql.row.WritableRow;
import de.fabiexe.sjql.util.SQLUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public abstract class BasicDatabase implements Database {
    protected final DataSource dataSource;

    public BasicDatabase(@NotNull DataSource dataSource) {
        this.dataSource = dataSource;
    }

    protected abstract boolean isAutoGenerated(@NotNull Column<?> column);
    protected abstract @Nullable String getPrimaryKeyAddition(@NotNull Column<?> column);

    public @NotNull DataSource getDataSource() {
        return dataSource;
    }

    @Override
    public void createTable(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            StringBuilder sql = new StringBuilder("CREATE TABLE IF NOT EXISTS ")
                    .append(table.getName())
                    .append(" (");

            List<Column<?>> columns = table.getColumns();
            List<Column<?>> primaryKeys = new ArrayList<>();
            for (int i = 0; i < columns.size(); i++) {
                Column<?> column = columns.get(i);
                sql.append(column.name()).append(' ').append(getColumnType(column));

                if (column.isPrimaryKey()) {
                    primaryKeys.add(column);
                }

                String primaryKeyAddition = getPrimaryKeyAddition(column);
                if (primaryKeyAddition != null) {
                    sql.append(' ').append(primaryKeyAddition);
                }

                Expression defaultValue = column.defaultValue();
                if (defaultValue != null) {
                    sql.append(" DEFAULT ").append(SQLUtil.buildSqlWithoutPlaceholders(defaultValue));
                }

                if (i < columns.size() - 1) {
                    sql.append(", ");
                }
            }

            if (!primaryKeys.isEmpty()) {
                sql.append(", PRIMARY KEY (");
                for (int i = 0; i < primaryKeys.size(); i++) {
                    sql.append(primaryKeys.get(i).name());
                    if (i < primaryKeys.size() - 1) {
                        sql.append(", ");
                    }
                }
                sql.append(")");
            }

            sql.append(");");

            try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
                statement.executeUpdate();
            }
        }
    }

    @Override
    public void deleteTable(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String sql = "DROP TABLE IF EXISTS " + table.getName();
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.execute();
            }
        }
    }

    @Override
    public <T> @NotNull DeleteStatement delete(@NotNull Table<T> table) {
        return new BasicDeleteStatement<>(table, dataSource::getConnection);
    }

    @Override
    public <T> @NotNull UpdateStatement update(@NotNull Table<T> table, @NotNull java.util.function.Consumer<de.fabiexe.sjql.row.WritableRow> builder) {
        return new BasicUpdateStatement<>(table, dataSource::getConnection, builder);
    }

    @Override
    public <T> void insert(@NotNull Table<T> table, @NotNull WritableRow row) throws SQLException {
        for (Column<?> column : table.getColumns()) {
            if (!row.contains(column) && column.defaultValue() == null && !isAutoGenerated(column)) {
                throw new IllegalArgumentException("Column " + column.name() + " is required but not set in the row");
            }
        }

        try (Connection connection = dataSource.getConnection()) {
            StringBuilder sql = new StringBuilder("INSERT INTO ")
                    .append(table.getName())
                    .append(" (");

            boolean first = true;
            for (Column<?> column : table.getColumns()) {
                if (!row.contains(column)) {
                    continue;
                }
                if (first) {
                    first = false;
                } else {
                    sql.append(", ");
                }
                sql.append(column.name());
            }

            sql.append(") VALUES (");

            first = true;
            for (Column<?> column : table.getColumns()) {
                if (!row.contains(column)) {
                    continue;
                }
                if (first) {
                    first = false;
                } else {
                    sql.append(", ");
                }
                sql.append("?");
            }

            sql.append(");");

            try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
                int index = 1;
                for (Column<?> column : table.getColumns()) {
                    if (!row.contains(column)) {
                        continue;
                    }
                    if (row.get(column) instanceof ConstantExpression<?> expression) {
                        SQLUtil.setObject(statement, index++, expression);
                    }
                }
                statement.executeUpdate();
            }
        }
    }

    @Override
    public @NotNull <T> Query<List<ReadableRow<T>>> selectRows(@NotNull Table<T> table) {
        return new BasicRowQuery<>(table, dataSource::getConnection);
    }

    @Override
    public @NotNull <T> Query<List<T>> select(@NotNull Table<T> table) {
        return new BasicValueQuery<>(table, dataSource::getConnection);
    }

    protected @NotNull String getColumnType(Column<?> column) {
        return switch (column) {
            case IntColumn _ -> "INT";
            case DoubleColumn _ -> "DOUBLE";
            case StringColumn stringColumn -> "VARCHAR(" + stringColumn.getMaxLength() + ")";
            case LongColumn _ -> "BIGINT";
            case FloatColumn _ -> "FLOAT";
            case BooleanColumn _ -> "BOOLEAN";
            case UUIDColumn _ -> "UUID";
        };
    }
}
