package de.fabiexe.sjql.database;

import de.fabiexe.sjql.*;
import de.fabiexe.sjql.column.*;
import de.fabiexe.sjql.expression.Expression;
import de.fabiexe.sjql.expression.constant.ConstantExpression;
import de.fabiexe.sjql.expression.constant.NullExpression;
import de.fabiexe.sjql.query.BasicDeleteStatement;
import de.fabiexe.sjql.query.BasicRowQuery;
import de.fabiexe.sjql.query.BasicUpdateStatement;
import de.fabiexe.sjql.query.BasicValueQuery;
import de.fabiexe.sjql.row.ReadableRow;
import de.fabiexe.sjql.row.WritableRow;
import de.fabiexe.sjql.util.SQLUtil;
import org.jspecify.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;

/** Base implementation of {@link Database} for JDBC data sources. */
public abstract class BasicDatabase implements Database {
    /** The data source used to obtain database connections. */
    protected final DataSource dataSource;

    /**
     * Creates a new database instance for the given data source.
     *
     * @param dataSource the data source to use
     */
    public BasicDatabase(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * Checks whether the given column is auto-generated by the database.
     *
     * @param column the column to check
     * @return {@code true} if the column value is auto-generated
     */
    protected abstract boolean isAutoGenerated(Column<?> column);

    /**
     * Gets the database-specific SQL fragment to add to an auto-generated primary key column,
     * or {@code null} if no addition is needed.
     *
     * @param column the column to generate the fragment for
     * @return the SQL fragment, or {@code null}
     */
    protected abstract @Nullable String getPrimaryKeyAddition(Column<?> column);

    /**
     * Escapes the given table name for safe use in SQL queries.
     *
     * @param name the table name to escape
     * @return the escaped table name
     */
    public abstract String escapeTableName(String name);

    /**
     * Escapes the given column name for safe use in SQL queries.
     *
     * @param name the column name to escape
     * @return the escaped column name
     */
    public abstract String escapeColumnName(String name);

    /**
     * Gets the data source used by this database.
     *
     * @return the data source
     */
    public DataSource getDataSource() {
        return dataSource;
    }

    @Override
    public void createTable(Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            StringBuilder sql = new StringBuilder("CREATE TABLE IF NOT EXISTS ")
                    .append(escapeTableName(table.getName()))
                    .append(" (");

            List<Column<?>> columns = table.getColumns();
            List<Column<?>> primaryKeys = new ArrayList<>();
            for (int i = 0; i < columns.size(); i++) {
                Column<?> column = columns.get(i);
                sql.append(escapeColumnName(column.name())).append(' ').append(getColumnType(column));

                if (column.isPrimaryKey()) {
                    primaryKeys.add(column);
                }

                String primaryKeyAddition = getPrimaryKeyAddition(column);
                if (primaryKeyAddition != null) {
                    sql.append(' ').append(primaryKeyAddition);
                }

                if (column.isNotNull()) {
                    sql.append(" NOT NULL");
                }

                if (column.isUnique() && !column.isPrimaryKey()) {
                    sql.append(" UNIQUE");
                }

                Expression defaultValue = column.defaultValue();
                if (defaultValue != null) {
                    sql.append(" DEFAULT ").append(SQLUtil.buildSqlWithoutPlaceholders(this, defaultValue));
                }

                if (i < columns.size() - 1) {
                    sql.append(", ");
                }
            }

            if (!primaryKeys.isEmpty()) {
                sql.append(", PRIMARY KEY (");
                for (int i = 0; i < primaryKeys.size(); i++) {
                    sql.append(escapeColumnName(primaryKeys.get(i).name()));
                    if (i < primaryKeys.size() - 1) {
                        sql.append(", ");
                    }
                }
                sql.append(")");
            }

            for (Table.UniqueConstraint uniqueConstraint : table.getUniqueConstraints()) {
                sql.append(", UNIQUE (");
                List<Column<?>> constraintColumns = uniqueConstraint.columns();
                for (int i = 0; i < constraintColumns.size(); i++) {
                    sql.append(escapeColumnName(constraintColumns.get(i).name()));
                    if (i < constraintColumns.size() - 1) {
                        sql.append(", ");
                    }
                }
                sql.append(")");
            }

            sql.append(");");

            try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
                statement.executeUpdate();
            }
        }
    }

    @Override
    public void deleteTable(Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String sql = "DROP TABLE IF EXISTS " + escapeTableName(table.getName());
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.execute();
            }
        }
    }

    @Override
    public <T extends @Nullable Object> DeleteStatement delete(Table<T> table) {
        return new BasicDeleteStatement<>(this, table, dataSource::getConnection);
    }

    @Override
    public <T extends @Nullable Object> UpdateStatement update(Table<T> table, Consumer<WritableRow> builder) {
        return new BasicUpdateStatement<>(this, table, dataSource::getConnection, builder);
    }

    @Override
    public <T extends @Nullable Object> void insert(Table<T> table, WritableRow row) throws SQLException {
        for (Column<?> column : table.getColumns()) {
            if (column.isNotNull()) {
                if (row.get(column) instanceof NullExpression) {
                    throw new IllegalArgumentException("Column " + column.name() + " is NOT NULL but set to null");
                }
                if (!row.contains(column) && column.defaultValue() == null && !isAutoGenerated(column)) {
                    throw new IllegalArgumentException("Column " + column.name() + " is required but not set in the row");
                }
            }
        }

        try (Connection connection = dataSource.getConnection()) {
            StringBuilder sql = new StringBuilder("INSERT INTO ")
                    .append(escapeTableName(table.getName()))
                    .append(" (");

            boolean first = true;
            for (Column<?> column : table.getColumns()) {
                if (!row.contains(column)) {
                    continue;
                }
                if (first) {
                    first = false;
                } else {
                    sql.append(", ");
                }
                sql.append(escapeColumnName(column.name()));
            }

            sql.append(") VALUES (");

            List<ConstantExpression<?>> parameters = new ArrayList<>();
            first = true;
            for (Column<?> column : table.getColumns()) {
                if (!row.contains(column)) {
                    continue;
                }
                if (first) {
                    first = false;
                } else {
                    sql.append(", ");
                }
                Expression expression = Objects.requireNonNull(row.get(column));
                Map.Entry<String, List<ConstantExpression<?>>> sqlEntry = SQLUtil.buildSql(this, expression);
                sql.append(sqlEntry.getKey());
                parameters.addAll(sqlEntry.getValue());
            }

            sql.append(");");

            try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
                for (int i = 0; i < parameters.size(); i++) {
                    SQLUtil.setObject(statement, i + 1, parameters.get(i));
                }
                statement.executeUpdate();
            }
        }
    }

    @Override
    public <T extends @Nullable Object> Query<List<ReadableRow>> selectRows(Table<T> table) {
        return new BasicRowQuery<>(this, table, dataSource::getConnection);
    }

    @Override
    public <T extends @Nullable Object> Query<List<T>> select(Table<T> table) {
        return new BasicValueQuery<>(this, table, dataSource::getConnection);
    }

    /**
     * Gets the SQL type declaration for the given column.
     *
     * @param column the column
     * @return the SQL type declaration
     */
    protected String getColumnType(Column<?> column) {
        return switch (column) {
            case IntColumn _ -> "INT";
            case DoubleColumn _ -> "DOUBLE";
            case StringColumn stringColumn -> "VARCHAR(" + stringColumn.getMaxLength() + ")";
            case LongColumn _ -> "BIGINT";
            case FloatColumn _ -> "FLOAT";
            case BooleanColumn _ -> "BOOLEAN";
            case UUIDColumn _ -> "UUID";
            case TimestampColumn _ -> "TIMESTAMP";
            case ComplexColumn<?, ?> complexColumn -> getColumnType(complexColumn.getBase());
        };
    }
}