package de.fabiexe.sjql.database;

import de.fabiexe.sjql.*;
import de.fabiexe.sjql.column.*;
import de.fabiexe.sjql.expression.Expression;
import de.fabiexe.sjql.expression.constant.ConstantExpression;
import de.fabiexe.sjql.expression.constant.NullExpression;
import de.fabiexe.sjql.query.BasicDeleteStatement;
import de.fabiexe.sjql.query.BasicRowQuery;
import de.fabiexe.sjql.query.BasicUpdateStatement;
import de.fabiexe.sjql.query.BasicValueQuery;
import de.fabiexe.sjql.row.ReadableRow;
import de.fabiexe.sjql.row.WritableRow;
import de.fabiexe.sjql.util.SQLUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Consumer;

/** Base implementation of {@link Database} for JDBC data sources. */
public abstract class BasicDatabase implements Database {
    /** The data source used to obtain database connections. */
    protected final DataSource dataSource;

    /**
     * Creates a new database instance for the given data source.
     *
     * @param dataSource the data source to use
     */
    public BasicDatabase(@NotNull DataSource dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * Checks whether the given column is auto-generated by the database.
     *
     * @param column the column to check
     * @return {@code true} if the column value is auto-generated
     */
    protected abstract boolean isAutoGenerated(@NotNull Column<?> column);

    /**
     * Gets the database-specific SQL fragment to add to an auto-generated primary key column,
     * or {@code null} if no addition is needed.
     *
     * @param column the column to generate the fragment for
     * @return the SQL fragment, or {@code null}
     */
    protected abstract @Nullable String getPrimaryKeyAddition(@NotNull Column<?> column);

    /**
     * Gets the data source used by this database.
     *
     * @return the data source
     */
    public @NotNull DataSource getDataSource() {
        return dataSource;
    }

    @Override
    public void createTable(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            StringBuilder sql = new StringBuilder("CREATE TABLE IF NOT EXISTS `")
                    .append(table.getName())
                    .append("` (");

            List<Column<?>> columns = table.getColumns();
            List<Column<?>> primaryKeys = new ArrayList<>();
            for (int i = 0; i < columns.size(); i++) {
                Column<?> column = columns.get(i);
                sql.append('`').append(column.name()).append("` ").append(getColumnType(column));

                if (column.isPrimaryKey()) {
                    primaryKeys.add(column);
                }

                String primaryKeyAddition = getPrimaryKeyAddition(column);
                if (primaryKeyAddition != null) {
                    sql.append(' ').append(primaryKeyAddition);
                }

                if (column.isNotNull()) {
                    sql.append(" NOT NULL");
                }

                Expression defaultValue = column.defaultValue();
                if (defaultValue != null) {
                    sql.append(" DEFAULT ").append(SQLUtil.buildSqlWithoutPlaceholders(defaultValue));
                }

                if (i < columns.size() - 1) {
                    sql.append(", ");
                }
            }

            if (!primaryKeys.isEmpty()) {
                sql.append(", PRIMARY KEY (");
                for (int i = 0; i < primaryKeys.size(); i++) {
                    sql.append('`').append(primaryKeys.get(i).name()).append('`');
                    if (i < primaryKeys.size() - 1) {
                        sql.append(", ");
                    }
                }
                sql.append(")");
            }

            sql.append(");");

            try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
                statement.executeUpdate();
            }
        }
    }

    @Override
    public void deleteTable(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String sql = "DROP TABLE IF EXISTS `" + table.getName() + "`";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.execute();
            }
        }
    }

    @Override
    public <T> @NotNull DeleteStatement delete(@NotNull Table<T> table) {
        return new BasicDeleteStatement<>(table, dataSource::getConnection);
    }

    @Override
    public <T> @NotNull UpdateStatement update(@NotNull Table<T> table, @NotNull Consumer<WritableRow> builder) {
        return new BasicUpdateStatement<>(table, dataSource::getConnection, builder);
    }

    @Override
    public <T> void insert(@NotNull Table<T> table, @NotNull WritableRow row) throws SQLException {
        for (Column<?> column : table.getColumns()) {
            if (column.isNotNull()) {
                if (row.get(column) instanceof NullExpression) {
                    throw new IllegalArgumentException("Column " + column.name() + " is NOT NULL but set to null");
                }
                if (!row.contains(column) && column.defaultValue() == null && !isAutoGenerated(column)) {
                    throw new IllegalArgumentException("Column " + column.name() + " is required but not set in the row");
                }
            }
        }

        try (Connection connection = dataSource.getConnection()) {
            StringBuilder sql = new StringBuilder("INSERT INTO `")
                    .append(table.getName())
                    .append("` (");

            boolean first = true;
            for (Column<?> column : table.getColumns()) {
                if (!row.contains(column)) {
                    continue;
                }
                if (first) {
                    first = false;
                } else {
                    sql.append(", ");
                }
                sql.append('`').append(column.name()).append('`');
            }

            sql.append(") VALUES (");

            List<ConstantExpression<?>> parameters = new ArrayList<>();
            first = true;
            for (Column<?> column : table.getColumns()) {
                if (!row.contains(column)) {
                    continue;
                }
                if (first) {
                    first = false;
                } else {
                    sql.append(", ");
                }
                Expression expression = Objects.requireNonNull(row.get(column));
                Map.Entry<String, List<ConstantExpression<?>>> sqlEntry = SQLUtil.buildSql(expression);
                sql.append(sqlEntry.getKey());
                parameters.addAll(sqlEntry.getValue());
            }

            sql.append(");");

            try (PreparedStatement statement = connection.prepareStatement(sql.toString())) {
                for (int i = 0; i < parameters.size(); i++) {
                    SQLUtil.setObject(statement, i + 1, parameters.get(i));
                }
                statement.executeUpdate();
            }
        }
    }

    @Override
    public @NotNull <T> Query<List<ReadableRow<T>>> selectRows(@NotNull Table<T> table) {
        return new BasicRowQuery<>(table, dataSource::getConnection);
    }

    @Override
    public @NotNull <T> Query<List<T>> select(@NotNull Table<T> table) {
        return new BasicValueQuery<>(table, dataSource::getConnection);
    }

    /**
     * Gets the SQL type declaration for the given column.
     *
     * @param column the column
     * @return the SQL type declaration
     */
    protected @NotNull String getColumnType(Column<?> column) {
        return switch (column) {
            case IntColumn _ -> "INT";
            case DoubleColumn _ -> "DOUBLE";
            case StringColumn stringColumn -> "VARCHAR(" + stringColumn.getMaxLength() + ")";
            case LongColumn _ -> "BIGINT";
            case FloatColumn _ -> "FLOAT";
            case BooleanColumn _ -> "BOOLEAN";
            case UUIDColumn _ -> "UUID";
            case TimestampColumn _ -> "TIMESTAMP";
            case ComplexColumn<?, ?> complexColumn -> getColumnType(complexColumn.getBase());
        };
    }
}
