package de.fabiexe.sjql.database;

import de.fabiexe.sjql.Table;
import de.fabiexe.sjql.column.Column;
import de.fabiexe.sjql.column.IntColumn;
import de.fabiexe.sjql.column.LongColumn;
import de.fabiexe.sjql.column.UUIDColumn;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class H2Database extends BasicDatabase {
    public H2Database(@NotNull DataSource dataSource) {
        super(dataSource);
    }

    @Override
    protected boolean isAutoGenerated(@NotNull Column<?> column) {
        return column.isPrimaryKey() &&
                (column instanceof IntColumn || column instanceof LongColumn || column instanceof UUIDColumn);
    }

    @Override
    protected @Nullable String getPrimaryKeyAddition(@NotNull Column<?> column) {
        return switch (column) {
            case IntColumn _ when column.isPrimaryKey() -> "AUTO_INCREMENT";
            case LongColumn _ when column.isPrimaryKey() -> "AUTO_INCREMENT";
            case UUIDColumn _ when column.isPrimaryKey() -> "DEFAULT RANDOM_UUID()";
            default -> null;
        };
    }

    @Override
    public boolean tableExists(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String tableName = table.getName().toUpperCase();
            String sql = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = '" + tableName + "'";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        return resultSet.getInt(1) > 0;
                    } else {
                        return false;
                    }
                }
            }
        }
    }
}
