package de.fabiexe.sjql.database;

import de.fabiexe.sjql.Table;
import de.fabiexe.sjql.column.Column;
import de.fabiexe.sjql.column.IntColumn;
import de.fabiexe.sjql.column.LongColumn;
import de.fabiexe.sjql.column.UUIDColumn;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class PostgreSQLDatabase extends BasicDatabase {
    public PostgreSQLDatabase(@NotNull DataSource dataSource) {
        super(dataSource);
    }

    @Override
    protected boolean isAutoGenerated(@NotNull Column<?> column) {
        return column.isPrimaryKey() &&
                (column instanceof IntColumn || column instanceof LongColumn || column instanceof UUIDColumn);
    }

    @Override
    protected @Nullable String getPrimaryKeyAddition(@NotNull Column<?> column) {
        return switch (column) {
            case UUIDColumn _ when column.isPrimaryKey() -> "DEFAULT gen_random_uuid()";
            default -> null;
        };
    }

    @Override
    protected @NotNull String getColumnType(Column<?> column) {
        return switch (column) {
            case IntColumn _ when column.isPrimaryKey() -> "SERIAL";
            case LongColumn _ when column.isPrimaryKey() -> "BIGSERIAL";
            default -> super.getColumnType(column);
        };
    }

    @Override
    public boolean tableExists(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String sql = "SELECT COUNT(*) FROM information_schema.tables WHERE table_name = ?";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setString(1, table.getName().toLowerCase());
                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        return resultSet.getInt(1) > 0;
                    }
                }
            }
        }
        return false;
    }
}
