package de.fabiexe.sjql.database;

import de.fabiexe.sjql.Table;
import de.fabiexe.sjql.column.Column;
import de.fabiexe.sjql.column.IntColumn;
import de.fabiexe.sjql.column.LongColumn;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class SQLiteDatabase extends BasicDatabase {
    public SQLiteDatabase(@NotNull DataSource dataSource) {
        super(dataSource);
    }

    @Override
    protected boolean isAutoGenerated(@NotNull Column<?> column) {
        return column.isPrimaryKey() &&
                (column instanceof IntColumn || column instanceof LongColumn);
    }

    @Override
    protected @Nullable String getPrimaryKeyAddition(@NotNull Column<?> column) {
        return switch (column) {
            case IntColumn _, LongColumn _ when column.isPrimaryKey() -> "AUTOINCREMENT";
            default -> super.getColumnType(column);
        };
    }

    @Override
    protected @NotNull String getColumnType(Column<?> column) {
        return switch (column) {
            case IntColumn _ -> "INTEGER";
            default -> super.getColumnType(column);
        };
    }

    @Override
    public boolean tableExists(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String sql = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='" + table.getName() + "'";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                ResultSet resultSet = statement.executeQuery();
                return resultSet.next() && resultSet.getInt(1) > 0;
            }
        }
    }
}
