package de.fabiexe.sjql.database;

import de.fabiexe.sjql.Table;
import de.fabiexe.sjql.column.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class SQLiteDatabase extends BasicDatabase {
    public SQLiteDatabase(@NotNull DataSource dataSource) {
        super(dataSource);
    }

    @Override
    protected boolean isAutoGenerated(@NotNull Column<?> column) {
        return column.isPrimaryKey() &&
                (column instanceof IntColumn || column instanceof LongColumn || column instanceof UUIDColumn);
    }

    @Override
    protected @Nullable String getPrimaryKeyAddition(@NotNull Column<?> column) {
        return switch (column) {
            case UUIDColumn _ when column.isPrimaryKey() -> """
                    DEFAULT (
                        lower(hex(randomblob(4))) || '-' ||
                        lower(hex(randomblob(2))) || '-4' ||
                        substr(lower(hex(randomblob(2))),2) || '-' ||
                        substr('89ab', abs(random()) % 4 + 1, 1) ||
                        substr(lower(hex(randomblob(2))),2) || '-' ||
                        lower(hex(randomblob(6)))
                    )""";
            default -> null;
        };
    }

    @Override
    protected @NotNull String getColumnType(Column<?> column) {
        return switch (column) {
            case IntColumn _, LongColumn _ -> "INTEGER";
            case UUIDColumn _ -> "TEXT";
            case TimestampColumn _ -> "DATETIME";
            default -> super.getColumnType(column);
        };
    }

    @Override
    public boolean tableExists(@NotNull Table<?> table) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String sql = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='" + table.getName() + "'";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                ResultSet resultSet = statement.executeQuery();
                return resultSet.next() && resultSet.getInt(1) > 0;
            }
        }
    }
}
